language: php

php:
  - 5.3.3
  - 5.3
  - 5.4

before_install:
    - echo '[Installing Prerequisites]'
    - ./install.sh > /dev/null 2>&1

script: phpunit

after_script:
    - cat test/coverage/coverage.txt
